---
name: 1- Test Django & MySQL
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  django_mysql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      MYSQL_DATABASE: cfeblog_db
      MYSQL_USER: cfe_blog_user
      MYSQL_ROOT_PASSWORD: 2mLTcmdPzU2LOa0TpAlLPoNf1XtIKsKvNn5WBiszczs
      MYSQL_TCP_PORT: 3306
      MYSQL_HOST: '127.0.0.1'
      GITHUB_ACTIONS: true
      DJANGO_SECRET_KEY: test-key-not-good
      DATABASE_BACKEND: mysql
    services:
      mysql:
        image: mysql:8.0.28
        env:
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_HOST: ${{ env.MYSQL_HOST }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
        ports:
          - 3306:3306
        options:
          --health-cmd="mysqladmin ping" -health-interval=10s
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with: 
          python-version: "3.10"
      - name: Install requirements
        run: |
          pip install -r requirements.txt
      - name: Run Tests
        env:
          DEBUG: "0"
          MYSQL_USER: "root"
          DATABASE_BACKEND: ${{ env.DATABASE_BACKEND }}
          DJANGO_SECRET_KEY: ${{ env.DJANGO_SECRET_KEY }}
        run: |
          python manage.py test